version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siroko-prueba-tecnica
    image: siroko-image
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - .:/var/www/symfony
    working_dir: /app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  home:
